services:

    #
    # Generators
    #
    beloop.generator.random_string:
        class: Beloop\Component\Core\Generator\RandomGenerator

    beloop.generator.sha1:
        class: Beloop\Component\Core\Generator\Sha1Generator
        arguments:
            - '@beloop.generator.random_string'

    beloop.generator.uniqid:
        class: Beloop\Component\Core\Generator\UniqIdGenerator
