services:

    #
    # Abstract Doctrine ObjectManager
    #
    beloop.abstract_manager:
        class: Doctrine\Common\Persistence\ObjectManager
        factory:
            - '@beloop.provider.manager'
            - getManagerByEntityNamespace
        abstract: true

    #
    # Abstract Doctrine Repository
    #
    beloop.abstract_repository:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory:
            - '@beloop.provider.repository'
            - getRepositoryByEntityNamespace
        abstract: true